apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: desec-api-token
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-backend
    kind: ClusterSecretStore
  target:
    name: desec-api-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: desec-api-token
