apiVersion: v1
kind: ConfigMap
metadata:
  name: homelab-globals
  namespace: default
data:
  DOMAIN: "${DOMAIN}"
  ACME_EMAIL: "${ACME_EMAIL}"
  TXT_OWNER_ID: "${TXT_OWNER_ID}"     # e.g. k3s-lab or k3s-lab-sandbox
  VW_BACKUP_REMOTE_TYPE: "${VW_BACKUP_REMOTE_TYPE}"
  VW_BACKUP_LOCATION: "${VW_BACKUP_LOCATION}"
  VW_URL: "${VW_URL}"
  GIT_REPO_URL: "${GIT_REPO_URL}"
