apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: desec-api-token
  namespace: cert-manager
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-backend
    kind: ClusterSecretStore
  target:
    # This must match the exact secret name cert-manager is looking for
    name: desec-api-token
    creationPolicy: Owner
  data:
    - secretKey: token # The key inside the Kubernetes secret
      remoteRef:
        key: desec-api-token # The name of the secret in Azure Key Vault
