apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/globals
  - vaultwarden.yaml
  - vaultwarden-backup-credentials-sync.yaml
  - vaultwarden-backup-cronjob.yaml

replacements:
  - source:
      kind: ConfigMap
      name: homelab-globals
      fieldPath: data.DOMAIN
    targets:
      - select:
          kind: Ingress
          name: vaultwarden-ingress
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
        options:
          delimiter: "."
          index: 1
