# /etc/rancher/k3s/config.yaml on KC01
node-ip: "${CONTROL_PLANE_IP}"
flannel-iface: "${INTERFACE}"
write-kubeconfig-mode: "0644"  #home lab convenience, allows non-root users to read the kubeconfig
node-taint:
  - "node-role.kubernetes.io/control-plane:NoSchedule"
node-label:
  - "node-type=control-plane"
  - "workload-type=infra"

